# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build:
    desc: Build backend and launcher together
    deps:
      - task: build-backend
      - task: build-frontend
      - task: build-launcher

  build-backend:
    dir: ./backend
    cmds:
      - go build -o dist/main.bin .

  build-frontend:
    dir: ./frontend
    cmds:
      - bun run build

  build-launcher:
    dir: ./launcher-rust
    cmds:
      - bun tauri build

  dev:
    desc: Run backend and launcher together
    deps:
      - dev-backend
      - dev-frontend
      - dev-launcher
      - dev-typegen

  dev-backend:
    desc: Run backend server
    dir: ./backend
    cmds:
      - go run -tags automigrate . serve

  dev-frontend:
    desc: Run frontend server
    dir: ./frontend
    cmds:
      - bun run dev

  dev-launcher:
    desc: Run launcher
    dir: ./launcher-rust
    cmds:
      - bun run tauri dev

  dev-typegen:
    cmds:
      - bun run scripts/typegen-watcher.ts

  sign-launcher:
    dir: ./launcher-rust
    cmds:
      - bunx tauri signer generate -w ~/.tauri/zapuskalka.key
