# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build:
    desc: Build backend and launcher together
    deps:
      - task: build-backend
      - task: build-frontend
      - task: build-launcher

  build-backend:
    dir: ./backend
    cmds:
      - go build -o dist/main.bin .

  build-frontend:
    dir: ./apps/frontend
    cmds:
      - bun run build

  build-launcher:
    dir: ./apps/launcher-rust
    cmds:
      - bun tauri build

  dev:
    desc: Run backend and launcher together
    deps:
      - dev-backend
      - dev-av-service
      - dev-frontend
      - dev-launcher

  dev-backend:
    desc: Run backend server
    dir: ./backend
    cmds:
      - go run -tags automigrate . serve

  dev-av-service:
    desc: Run av service
    cmds:
      - docker build -f av.Dockerfile --platform linux/amd64 -t av-scanner:latest .
      - docker run --platform linux/amd64 --rm -d --name av-scanner --env-file apps/av-service/.env -e POCKETBASE_URL=http://host.docker.internal:8090 av-scanner:latest

  dev-frontend:
    desc: Run frontend server
    dir: ./apps/frontend
    cmds:
      - bun run dev

  dev-launcher:
    desc: Run launcher
    dir: ./apps/launcher-rust
    cmds:
      - bun run tauri dev

  dev-typegen:
    cmds:
      - bun run scripts/typegen-watcher.ts

  sign-launcher:
    dir: ./apps/launcher-rust
    cmds:
      - bunx tauri signer generate -w ~/.tauri/zapuskalka.key
