# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build:
    dir: ./launcher
    cmds:
      - wails build -nsis

  dev:
    desc: Run backend and launcher together
    deps:
      - task: dev-backend
      - task: dev-launcher
      - task: dev-typegen

  dev-backend:
    desc: Run backend server
    dir: ./backend
    cmds:
      - go run -tags automigrate . serve

  dev-launcher:
    desc: Run launcher (Wails dev)
    dir: ./launcher
    cmds:
      - wails dev

  dev-typegen:
    cmds:
      - bun run typegen
      - bun run scripts/typegen-watcher.ts
