# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build:
    desc: Build backend and launcher together
    deps:
      - task: build-backend
      - task: build-launcher

  build-backend:
    dir: ./backend
    cmds:
      - go build -o dist/main.bin .

  build-launcher:
    dir: ./launcher-rust
    cmds:
      - bun tauri build

  dev:
    desc: Run backend and launcher together
    deps:
      - task: dev-backend
      - task: dev-launcher
      - task: dev-typegen

  dev-backend:
    desc: Run backend server
    dir: ./backend
    cmds:
      - go run -tags automigrate . serve

  dev-launcher:
    desc: Run launcher
    dir: ./launcher-rust
    cmds:
      - bun run tauri dev

  sign-launcher:
    dir: ./launcher-rust
    cmds:
      - bunx tauri signer generate -w ~/.tauri/zapuskalka.key

  dev-typegen:
    cmds:
      - bun run scripts/typegen-watcher.ts
