// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadStorageList() {
  return window['go']['main']['App']['LoadStorageList']();
}

export function OsOpenFolder() {
  return window['go']['main']['App']['OsOpenFolder']();
}

export function RunGame(arg1) {
  return window['go']['main']['App']['RunGame'](arg1);
}

export function SaveStorageList(arg1) {
  return window['go']['main']['App']['SaveStorageList'](arg1);
}
