// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LoadStorageList():Promise<Array<main.Storage>>;

export function OsOpenFolder():Promise<string>;

export function RunGame(arg1:string):Promise<void>;

export function SaveStorageList(arg1:Array<main.Storage>):Promise<void>;
